[package]
name = "uniffi-kmm-example-swift-interop"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish = false

[lib]
name = "uniffi_kmm_example_swift_interop"
crate-type = ["lib", "cdylib", "staticlib"]
path = "src/commonMain/rust/lib.rs"

[dependencies]
uniffi = { workspace = true }
