stages:
  - prepare
  - build

default:
  tags:
    - saas-linux-medium-amd64
  image: $CI_REGISTRY_IMAGE/build-image:latest

meta-build-image:
  image: docker:stable
  services:
    - docker:dind
  stage: prepare
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd .meta/build-image
    - docker build -t $CI_REGISTRY_IMAGE/build-image:latest .
    - docker push $CI_REGISTRY_IMAGE/build-image:latest

build-all:
  stage: build
  script:
    - cargo build --verbose
    - cargo test --verbose
    - ./gradlew build
  artifacts:
    when: always
    reports:
      junit: '**/test-results/*Test/*.xml'
