[workspace]
members = [
    "bindgen",
    "tests/callbacks/uniffi",
    "tests/coverall/uniffi",
    "tests/external-types/uniffi",
    "tests/futures/uniffi",
    "tests/keywords/uniffi",
    "tests/proc-macro/uniffi",
    "tests/trait-methods/uniffi",
]
resolver = "2"
