[package]
name = "uniffi-runtime"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "uniffi_runtime"
crate-type = ["cdylib", "staticlib"]
path = "src/commonMain/rust/lib.rs"

[dependencies]
uniffi = { workspace = true }
