[versions]

project = "0.1-SNAPSHOT"

kotlin = "1.9.20"

kotlinx-coroutines = "1.6.4"
kotlinx-atomicfu = "0.18.5"
kotlinx-datetime = "0.4.0"

okio = "3.2.0"
jna = "5.12.1"

kotest = "5.5.4"

[plugins]

[libraries]

kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-atomicfu-plugin = { group = "org.jetbrains.kotlinx", name = "atomicfu-gradle-plugin", version.ref = "kotlinx-atomicfu" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
