[package]
name = "uniffi-kmm-fixture-interface-throws"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "uniffi_kmm_fixture_interface_throws"
crate-type = ["cdylib", "staticlib"]
path = "src/commonMain/rust/lib.rs"

[dependencies]
thiserror = { workspace = true }
uniffi = { workspace = true }
