[package]
name = "uniffi-kmm-example-arithmetic-procmacro"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "uniffi_kmm_example_arithmetic_procmacro"
crate-type = ["cdylib", "staticlib"]
path = "src/commonMain/rust/lib.rs"

[dependencies]
uniffi = "0.28.3"
thiserror = "1.0"
