name: Publish to Maven Central

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Upload
        run: |
          echo "${{secrets.MAVEN_SIGNING_KEY_ARMOR_ASC}}" > ./signingkey.asc
          gpg --quiet --output $GITHUB_WORKSPACE/signingkey.gpg --dearmor ./signingkey.asc
          ./gradlew :build-logic:gradle-plugin:publishAndReleaseToMavenCentral -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/signingkey.gpg -Psigning.password='${{secrets.MAVEN_SIGNING_KEY_PASSPHRASE}}' -Psigning.keyId=${{secrets.MAVEN_SIGNING_KEY_ID}} -PmavenCentralUsername=${{secrets.MAVEN_CENTRAL_USERNAME}} -PmavenCentralPassword=${{secrets.MAVEN_CENTRAL_PASSWORD}} -PgithubRefName=${{ github.ref_name }}

  publish-runtime:
    runs-on: macos-15-xlarge
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Install Linux-Toolchain
        run: |
          brew tap messense/macos-cross-toolchains
          # install x86_64-unknown-linux-gnu toolchain
          brew install x86_64-unknown-linux-gnu
          # install aarch64-unknown-linux-gnu toolchain
          brew install aarch64-unknown-linux-gnu
          # install mingw-w64 targets
          brew install mingw-w64

      - name: Upload
        env:
          IPHONEOS_DEPLOYMENT_TARGET: '16.4'
          CC_x86_64_unknown_linux_gnu: x86_64-linux-gnu-gcc
          CXX_x86_64_unknown_linux_gnu: x86_64-linux-gnu-g++
          AR_x86_64_unknown_linux_gnu: x86_64-linux-gnu-ar
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: x86_64-linux-gnu-gcc
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
          AR_aarch64_unknown_linux_gnu: aarch64-linux-gnu-ar
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CARGO_TARGET_X86_64-PC-WINDOWS-GNU: x86_64-w64-mingw32-gcc
        run: |
          echo "${{secrets.MAVEN_SIGNING_KEY_ARMOR_ASC}}" > ./signingkey.asc
          gpg --quiet --output $GITHUB_WORKSPACE/signingkey.gpg --dearmor ./signingkey.asc
          ./gradlew :runtime:publishAndReleaseToMavenCentral -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/signingkey.gpg -Psigning.password='${{secrets.MAVEN_SIGNING_KEY_PASSPHRASE}}' -Psigning.keyId=${{secrets.MAVEN_SIGNING_KEY_ID}} -PmavenCentralUsername=${{secrets.MAVEN_CENTRAL_USERNAME}} -PmavenCentralPassword=${{secrets.MAVEN_CENTRAL_PASSWORD}} -PgithubRefName=${{ github.ref_name }} -PreleaseBuild=true    
