name: Run all tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: large-runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y \
            build-essential binutils android-sdk \
            gcc-mingw-w64 mingw-w64-x86-64-dev \
            libgtk-4-dev wget perl libssl-dev && \
          sudo rm -rf /var/lib/apt/lists/*
      
      - name: Install Zig
        run: |
          export ZIG_VERSION=0.12.1 && \
          export ZIG_BUILD=zig-linux-x86_64-$ZIG_VERSION && \
          mkdir -p $HOME/zig && cd $HOME/zig && \
          wget -c https://ziglang.org/download/$ZIG_VERSION/$ZIG_BUILD.tar.xz && \
          tar -xf $ZIG_BUILD.tar.xz && \
          printf "#! /bin/sh\n$HOME/zig/$ZIG_BUILD/zig cc -target aarch64-linux-gnu \"\$@\"" > aarch64-unknown-linux-gnu-cc.sh && \
          chmod 777 aarch64-unknown-linux-gnu-cc.sh && \
          mkdir -p $HOME/.cargo && \
          echo "[target.aarch64-unknown-linux-gnu]
          linker = \"$HOME/zig/aarch64-unknown-linux-gnu-cc.sh\"" > $HOME/.cargo/config.toml
      
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          yes | sdkmanager --install "build-tools;34.0.0" "platforms;android-34" "ndk;26.1.10909125"
          yes | sdkmanager --licenses
      
      - name: Build and Test
        run: |
          cargo build && \
          cargo test && \
          ./gradlew :build-logic:gradle-plugin:test && \
          ./gradlew build
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test-results/*Test/*.xml'

        